project :  
  owner: quickstart-eng@amazon.com
  s3_bucket: blueprintesting22
  regions:
    - eu-west-1
    - us-east-1
    - us-west-2
tests:
  default:
    template: ./cdk.out/AwsBiotechBlueprint.template.json
    regions:
    - us-east-1
    #- us-west-2
    - eu-west-1
